name: Deploy - Prod

on:
  workflow_dispatch:  # Permet de lancer manuellement le workflow
  push:
    branches:
      - main  # Déclenche le workflow lors des pushes sur la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to PlanetHoster
        run: |
          ssh -o StrictHostKeyChecking=no -p 2604 sonolocf@sonoloc71.fr "echo ok"
